# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Chapter 6

on:
  push:
    paths:
      - 'chapter-06/**' 
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17

    - name: Build with Maven
      working-directory: chapter-06/java/flying-high
      run: mvn -B verify

    - name: Archive Serenity BDD reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        retention-days: 3
        name: chapter-6-reports
        path: |
          chapter-06/flying-high/target/site/serenity/**/*
